repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: cargo fmt
      - id: cargo-check

  # pre-commit rust does not allow passing arguments to cargo clippy properly so
  # we use a local hook instead
  - repo: local
    hooks:
      - id: clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args:
          - --all-targets
          # - --all-features
          - "--"
          - "-D"
          - "warnings"
        types: [rust]
        pass_filenames: false
